spring:
  application:
    name: payment-microservice

eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:1111/eureka/

server: 
  port: 4444

error:
  whitelabel:
    enabled: false