spring:
  application:
    name: agreement-microservice

eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:1111/eureka/

server: 
  port: 3333

error:
  whitelabel:
    enabled: false