spring:
  application:
    name: evaluation-microservice

eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:1111/eureka/

server: 
  port: 2222

error:
  whitelabel:
    enabled: false